source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'
workspace 'KoloMarvel'
use_frameworks!

target 'KoloMarvel' do
  project 'KoloMarvel/KoloMarvel'

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for KoloMarvel
  pod 'SwiftLint' #used for linting
  pod 'Cache' #used for caching api responses
  
  target 'KoloMarvelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KoloMarvelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']
      cflags << '-fembed-bitcode'
      config.build_settings['OTHER_CFLAGS'] = cflags
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings.delete 'IOS_DEPLOYMENT_TARGET'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
    end
  end
end
